### ISSUE TITLE
Change files structure

### ISSUE THREAD

**Issue by Jeffveloper** [Inkacoders/Inka-homepage#20]
## Task

- [x] reorder css files
- [x] delete useless font classes
- [ ] fix css paths (main js files, images)
